language: node_js
node_js:
  - "7"
branches:
  only:
    - master

before_script:
  - npm install -g gulp-cli

script:
  - gulp build
  - gulp deploy


env:
  global:
    secure: gR5VU4DlAknGFWM1wEjxYy+/DieK9dP4uhceO0TziixXKuuhOupD74ODrE8YVyIYj7f4ph4ahEoBlV5LTqYyPjx6NR0wmIdab0bvyi8XMtDb0ipbfm2OyH07b891Wu7j8x2h6PnnR2VRWoIm1HRzM/GjfUTPtpzdZn3QNZraF9XN7/73guPJ3QQbFfh7qE3FU2ITueS2E2uGtiIqKgKTodvH9Hrj136uatweIdeh/CAmNcXClTo2bZzqZlSu4HEWGT/CBLyNAKywrM7y9a7ngOJR14Hzn3/ky87l50dB66ckHVyFT0Z0jgVafECXu2lOp8ArZS7WlirlrumB0Yg+p/vgw7BnrOvymKmaoef0Fq9Ow4KxHtHwQEr5yVNfNQpLWFZ9yYqlEwQNhoT+t04woKkwMKWriIiA+ylS7+rDzluVPYdOjV7gsH3by3m5gilmFAydEFKFuYJWQ5H18WJv1YpfosuHOB/S314sR6plQRCCJJRqFY0Gw9O3TGqScdTWyV4a215Ra1l6tjIjjlUtqQ3gqOgpzx1HgTTvlL9YagL5iVw6iwls2RlNkBV0LYU4XRAfMhy2IedGYdStky5rPQDom1CKonhxmjX413oE3EvuKONQeFwUvibqbhAiURd+VpEgu8vDmvzYIybb1W012y0Bhxex048WnUQGbXxuy4s=
